-- MySQL Script generated by MySQL Workbench
-- 2016年03月18日 星期五 15时14分52秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbwww58com_cmdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbwww58com_cmdb` ;

-- -----------------------------------------------------
-- Schema dbwww58com_cmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbwww58com_cmdb` DEFAULT CHARACTER SET utf8 ;
USE `dbwww58com_cmdb` ;

-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_idc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_idc` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_idc` (
  `idc_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'id',
  `idc_region` VARCHAR(45) NULL DEFAULT NULL,
  `idc_zone` VARCHAR(45) NULL DEFAULT NULL COMMENT '机房所在大区（华东、华北）',
  `idc_campus` VARCHAR(45) NULL DEFAULT NULL COMMENT '机房所在园区',
  `idc_address` TEXT(255) NULL DEFAULT NULL,
  `idc_phone` VARCHAR(45) NULL DEFAULT NULL,
  `idc_fax` VARCHAR(45) NULL DEFAULT NULL,
  `idc_email` VARCHAR(45) NULL DEFAULT NULL,
  `idc_owner_id` INT NULL DEFAULT NULL,
  `idc_enable_time` DATETIME NULL DEFAULT NULL,
  `idc_due_time` DATETIME NULL DEFAULT NULL,
  `idc_resource_type` TINYINT(4) NULL DEFAULT NULL,
  `idc_supplier` TEXT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idc_id`));


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_logic_section_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_logic_section_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_logic_section_type` (
  `logic_section_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `logic_section_type_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '逻辑区域类型名称',
  `logic_section_type_desc` VARCHAR(45) NULL DEFAULT NULL COMMENT '逻辑区域功能描述',
  PRIMARY KEY (`logic_section_type_id`));


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_logic_section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_logic_section` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_logic_section` (
  `logic_section_id` BIGINT(20) UNSIGNED NOT NULL,
  `logic_section_name` VARCHAR(45) NULL DEFAULT NULL,
  `idc_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `logic_section_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`logic_section_id`),
  INDEX `fk_t_logic_section_1_idx` (`idc_id` ASC),
  INDEX `fk_t_logic_section_2_idx` (`logic_section_type_id` ASC),
  CONSTRAINT `fk_t_logic_section_1`
    FOREIGN KEY (`idc_id`)
    REFERENCES `dbwww58com_cmdb`.`t_idc` (`idc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_logic_section_2`
    FOREIGN KEY (`logic_section_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_logic_section_type` (`logic_section_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_rack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_rack` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_rack` (
  `rack_id` BIGINT(20) UNSIGNED NOT NULL,
  `rack_name` VARCHAR(45) NULL DEFAULT NULL,
  `row_name` VARCHAR(45) NULL DEFAULT NULL,
  `row_num` INT NULL DEFAULT NULL,
  `rack_depth` INT NULL DEFAULT NULL,
  `rack_height` INT NULL DEFAULT NULL,
  `rack_width` INT NULL DEFAULT NULL,
  `rack_spec_height` INT NULL DEFAULT NULL,
  `rack_energy_type` TINYINT(4) NULL DEFAULT NULL,
  `rack_power_max` INT NULL DEFAULT NULL,
  `rack_power_rating` INT NULL DEFAULT NULL,
  `logic_section_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`rack_id`),
  INDEX `fk_t_rack_1_idx` (`logic_section_id` ASC),
  CONSTRAINT `fk_t_rack_1`
    FOREIGN KEY (`logic_section_id`)
    REFERENCES `dbwww58com_cmdb`.`t_logic_section` (`logic_section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_position` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_position` (
  `position_id` BIGINT(20) UNSIGNED NOT NULL,
  `rack_num` INT NULL DEFAULT NULL,
  `rack_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `positon_height` INT NULL DEFAULT NULL,
  `positon_spec_height` INT NULL DEFAULT NULL,
  `position_guide_type` INT NULL DEFAULT NULL,
  `position_guide_count` INT NULL DEFAULT NULL,
  `position_status` TINYINT(4) NULL DEFAULT NULL,
  `start_spec_height` INT NULL DEFAULT NULL,
  PRIMARY KEY (`position_id`),
  INDEX `fk_t_position_1_idx` (`rack_id` ASC),
  CONSTRAINT `fk_t_position_1`
    FOREIGN KEY (`rack_id`)
    REFERENCES `dbwww58com_cmdb`.`t_rack` (`rack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_asset` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_asset` (
  `asset_id` BIGINT(20) UNSIGNED NOT NULL,
  `asset_sn` VARCHAR(45) NULL DEFAULT NULL,
  `asset_is_device` TINYINT(4) NULL DEFAULT NULL,
  `asset_instock_time` DATETIME NULL DEFAULT NULL,
  `asset_first_use_time` DATETIME NULL DEFAULT NULL,
  `asset_outstock_time` DATETIME NULL DEFAULT NULL,
  `asset_warranty_due_time` DATETIME NULL DEFAULT NULL,
  `asset_receipt_time` DATETIME NULL DEFAULT NULL,
  `asset_on_shelf_time` DATETIME NULL DEFAULT NULL,
  `asset_off_shelf_time` DATETIME NULL DEFAULT NULL,
  `asset_last_update_time` DATETIME NULL DEFAULT NULL,
  `asset_status` TINYINT(4) NULL DEFAULT NULL,
  `asset_comment` TEXT NULL DEFAULT NULL,
  `position_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `device_type` TINYINT(4) NULL DEFAULT NULL,
  `order_item_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `asset_ower_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `asset_backup_ower_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `asset_belong_org_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `asset_operator_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `asset_backup_operator_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `asset_operator_org_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`asset_id`),
  INDEX `fk_t_asset_1_idx` (`position_id` ASC),
  CONSTRAINT `fk_t_asset_1`
    FOREIGN KEY (`position_id`)
    REFERENCES `dbwww58com_cmdb`.`t_position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_device_producer_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_device_producer_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_device_producer_type` (
  `device_producer_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `producer_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `producer_name` VARCHAR(45) NULL DEFAULT NULL,
  `device_type` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`device_producer_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_inc_server_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_inc_server_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_inc_server_type` (
  `inc_server_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `inc_server_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `inc_server_code` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`inc_server_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_server_device_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_server_device_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_server_device_type` (
  `server_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `device_producer_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_device_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `server_hight` INT(11) NULL DEFAULT NULL,
  `server_width` INT(11) NULL DEFAULT NULL,
  `server_depth` INT(11) NULL DEFAULT NULL,
  `server_electricity` VARCHAR(45) NULL DEFAULT NULL,
  `server_weight` INT(11) NULL DEFAULT NULL,
  `server_score` VARCHAR(45) NULL DEFAULT NULL,
  `server_minios` VARCHAR(45) NULL DEFAULT NULL,
  `server_max_power` INT(11) NULL DEFAULT NULL,
  `server_rated_power` INT(11) NULL DEFAULT NULL,
  `server_power_type` VARCHAR(45) NULL DEFAULT NULL,
  `server_mother_board_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`server_type_id`),
  INDEX `fk_t_server_device_type_1_idx` (`device_producer_type_id` ASC),
  CONSTRAINT `fk_t_server_device_type_1`
    FOREIGN KEY (`device_producer_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_device_producer_type` (`device_producer_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_os_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_os_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_os_type` (
  `os_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `os_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `os_type_version` VARCHAR(45) NULL DEFAULT NULL,
  `os_full_name` VARCHAR(45) NULL DEFAULT NULL,
  `os_default_version` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`os_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_server` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_server` (
  `server_id` BIGINT(20) UNSIGNED NOT NULL,
  `asset_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `inc_server_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_comment` TEXT NULL DEFAULT NULL,
  `server_bios_os` VARCHAR(45) NULL DEFAULT NULL,
  `server_device_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_status` TINYINT(4) NULL DEFAULT NULL,
  `server_bmc` VARCHAR(45) NULL DEFAULT NULL,
  `server_host_name` VARCHAR(45) NULL DEFAULT NULL,
  `os_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_kernel_version` VARCHAR(45) NULL DEFAULT NULL,
  `server_ads_status` TINYINT(4) NULL DEFAULT NULL,
  `server_ads_check_time` DATE NULL DEFAULT NULL,
  `server_ads_installed` TINYINT(4) NULL DEFAULT NULL,
  `server_ads_update_time` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`server_id`),
  INDEX `fk_t_server_1_idx` (`asset_id` ASC),
  INDEX `fk_t_server_2_idx` (`inc_server_type_id` ASC),
  INDEX `fk_t_server_3_idx` (`server_device_type_id` ASC),
  INDEX `fk_t_server_4_idx` (`os_type_id` ASC),
  CONSTRAINT `fk_t_server_2`
    FOREIGN KEY (`inc_server_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_inc_server_type` (`inc_server_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_server_3`
    FOREIGN KEY (`server_device_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_server_device_type` (`server_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_server_1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `dbwww58com_cmdb`.`t_asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_server_4`
    FOREIGN KEY (`os_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_os_type` (`os_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_network_interface`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_network_interface` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_network_interface` (
  `network_interface_id` BIGINT(20) UNSIGNED NOT NULL,
  `server_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `network_interface_name` VARCHAR(45) NULL DEFAULT NULL,
  `network_interface_type` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`network_interface_id`),
  INDEX `fk_t_network_interface_1_idx` (`server_id` ASC),
  CONSTRAINT `fk_t_network_interface_1`
    FOREIGN KEY (`server_id`)
    REFERENCES `dbwww58com_cmdb`.`t_server` (`server_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_idc_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_idc_module` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_idc_module` (
  `module_id` BIGINT(20) UNSIGNED NOT NULL,
  `module_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '机房网络模块名称',
  PRIMARY KEY (`module_id`),
  UNIQUE INDEX `module_id_UNIQUE` (`module_id` ASC));


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_nic_port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_nic_port` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_nic_port` (
  `nic_port_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '网卡端口id',
  `nic_port_name` VARCHAR(45) NOT NULL COMMENT '网口名称',
  `nic_port_speed` INT UNSIGNED NOT NULL COMMENT '网口传输速率，单位bit',
  `nic_port_transfer_medium` TINYINT(3) UNSIGNED NOT NULL COMMENT '网口传输介质',
  `nic_port_bandwidth` INT UNSIGNED NOT NULL COMMENT '网口最大带宽',
  `nic_port_mode` TINYINT(3) UNSIGNED NOT NULL COMMENT '工作模式（双工模式）',
  `nic_port_link_type` TINYINT(3) UNSIGNED NOT NULL COMMENT '网口链路类型(access, hybrid, trunk)',
  `asset_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '所属固资编号',
  `nic_port_num` INT UNSIGNED NOT NULL COMMENT '网口在设备上编号',
  `nic_port_level` TINYINT(4) UNSIGNED NOT NULL COMMENT '网口层级（设备网口级别与设备一致，服务器网口最低为0） ',
  `nic_port_planned_position_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nic_port_id`),
  INDEX `fk_t_nic_port_1_idx` (`asset_id` ASC),
  UNIQUE INDEX `nic_port_id_UNIQUE` (`nic_port_id` ASC),
  INDEX `fk_t_nic_port_2_idx` (`nic_port_planned_position_id` ASC),
  CONSTRAINT `fk_t_nic_port_1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `dbwww58com_cmdb`.`t_asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_nic_port_2`
    FOREIGN KEY (`nic_port_planned_position_id`)
    REFERENCES `dbwww58com_cmdb`.`t_position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_network_interface_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_network_interface_config` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_network_interface_config` (
  `network_interface_config_id` BIGINT(20) UNSIGNED NOT NULL,
  `network_interface_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `nic_port_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `network_interface_link_type` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`network_interface_config_id`),
  INDEX `fk_t_network_interface_config_1_idx` (`nic_port_id` ASC),
  INDEX `fk_t_network_interface_config_2_idx` (`network_interface_id` ASC),
  CONSTRAINT `fk_t_network_interface_config_1`
    FOREIGN KEY (`nic_port_id`)
    REFERENCES `dbwww58com_cmdb`.`t_nic_port` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_network_interface_config_2`
    FOREIGN KEY (`network_interface_id`)
    REFERENCES `dbwww58com_cmdb`.`t_network_interface` (`network_interface_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_network_interface_ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_network_interface_ip` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_network_interface_ip` (
  `network_interface_ip_id` BIGINT(20) UNSIGNED NOT NULL,
  `network_interface_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`network_interface_ip_id`),
  INDEX `fk_t_network_interface_ip_1_idx` (`network_interface_id` ASC),
  CONSTRAINT `fk_t_network_interface_ip_1`
    FOREIGN KEY (`network_interface_id`)
    REFERENCES `dbwww58com_cmdb`.`t_network_interface` (`network_interface_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_selection_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_selection_version` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_selection_version` (
  `server_selection_version_id` BIGINT(20) UNSIGNED NOT NULL,
  `server_selection_version_start_time` DATETIME NULL DEFAULT NULL,
  `server_selection_version_end_time` DATETIME NULL DEFAULT NULL,
  `server_selection_version_author_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_selection_versionnumber` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`server_selection_version_id`),
  UNIQUE INDEX `server_selection_version_id_UNIQUE` (`server_selection_version_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_server_selection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_server_selection` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_server_selection` (
  `server_selection_id` BIGINT(20) UNSIGNED NOT NULL,
  `inc_server_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_device_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `device_producer_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_selection_datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`server_selection_id`),
  INDEX `fk_t_server_selection_1_idx` (`inc_server_type_id` ASC),
  INDEX `fk_t_server_selection_2_idx` (`server_device_type_id` ASC),
  INDEX `fk_t_server_selection_3_idx` (`device_producer_type_id` ASC),
  CONSTRAINT `fk_t_server_selection_1`
    FOREIGN KEY (`inc_server_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_inc_server_type` (`inc_server_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_server_selection_2`
    FOREIGN KEY (`server_device_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_server_device_type` (`server_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_server_selection_3`
    FOREIGN KEY (`device_producer_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_device_producer_type` (`device_producer_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_selection_version_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_selection_version_record` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_selection_version_record` (
  `server_selection_version_record_id` BIGINT(20) UNSIGNED NOT NULL,
  `server_selection_version_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `server_selection_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`server_selection_version_record_id`),
  INDEX `fk_t_selection_version_record_1_idx` (`server_selection_version_id` ASC),
  INDEX `fk_t_selection_version_record_2_idx` (`server_selection_id` ASC),
  CONSTRAINT `fk_t_selection_version_record_1`
    FOREIGN KEY (`server_selection_version_id`)
    REFERENCES `dbwww58com_cmdb`.`t_selection_version` (`server_selection_version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_selection_version_record_2`
    FOREIGN KEY (`server_selection_id`)
    REFERENCES `dbwww58com_cmdb`.`t_server_selection` (`server_selection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_slot_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_slot_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_slot_type` (
  `slot_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `slot_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `slot_spec` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`slot_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_slot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_slot` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_slot` (
  `slot_id` BIGINT(20) UNSIGNED NOT NULL,
  `access_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `slot_type_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `slot_face_direction` TINYINT(4) NULL DEFAULT NULL,
  `insert_accessory_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `slot_num` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`slot_id`),
  INDEX `fk_t_slot_1_idx` (`access_id` ASC),
  INDEX `fk_t_slot_2_idx` (`slot_type_id` ASC),
  CONSTRAINT `fk_t_slot_2`
    FOREIGN KEY (`slot_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_slot_type` (`slot_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_slot_1`
    FOREIGN KEY (`access_id`)
    REFERENCES `dbwww58com_cmdb`.`t_asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_net_device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_net_device` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_net_device` (
  `net_device_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '网络设备id',
  `net_device_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '网络设备名称',
  `asset_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL COMMENT '网络设备固资id',
  `device_level` TINYINT(4) NULL DEFAULT NULL COMMENT '设备层级，服务器为最底层0',
  `t_net_devicecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`net_device_id`),
  INDEX `fk_t_net_device_1_idx` (`asset_id` ASC),
  CONSTRAINT `fk_t_net_device_1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `dbwww58com_cmdb`.`t_asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_nic_port_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_nic_port_link` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_nic_port_link` (
  `nic_port_link_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '网络连接id',
  `nic_port_id_upper` BIGINT(20) UNSIGNED NOT NULL COMMENT '网络连接上侧端口号',
  `nic_port_id_lower` BIGINT(20) UNSIGNED NOT NULL COMMENT '网络连接下侧端口号',
  `cable_type` TINYINT(3) NOT NULL COMMENT '连线类型（光纤、5类线）',
  PRIMARY KEY (`nic_port_link_id`),
  INDEX `fk_t_nic_port_link_1_idx` (`nic_port_id_upper` ASC),
  INDEX `fk_t_nic_port_link_2_idx` (`nic_port_id_lower` ASC),
  UNIQUE INDEX `nic_port_link_id_UNIQUE` (`nic_port_link_id` ASC),
  CONSTRAINT `fk_t_nic_port_link_1`
    FOREIGN KEY (`nic_port_id_upper`)
    REFERENCES `dbwww58com_cmdb`.`t_nic_port` (`nic_port_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_nic_port_link_2`
    FOREIGN KEY (`nic_port_id_lower`)
    REFERENCES `dbwww58com_cmdb`.`t_nic_port` (`nic_port_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '网络连接表，描述每一个网络端口连接的属性';


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_accessory_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_accessory_brand` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_accessory_brand` (
  `brand_id` BIGINT(20) UNSIGNED NOT NULL,
  `brand_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_accessory_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_accessory_type` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_accessory_type` (
  `accessory_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `accessory_type_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_accessory_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_accessory_store` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_accessory_store` (
  `accessory_store_id` BIGINT UNSIGNED NOT NULL,
  `accessory_store_name` VARCHAR(45) NULL DEFAULT NULL,
  `accessory_store_position` VARCHAR(45) NULL DEFAULT NULL,
  `accessory_store_poner` VARCHAR(45) NULL DEFAULT NULL,
  `asociated_idc_id` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`accessory_store_id`),
  INDEX `fk_t_accessory_store_1_idx` (`asociated_idc_id` ASC),
  CONSTRAINT `fk_t_accessory_store_1`
    FOREIGN KEY (`asociated_idc_id`)
    REFERENCES `dbwww58com_cmdb`.`t_idc` (`idc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_accessory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_accessory` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_accessory` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `accessory_status` INT NULL DEFAULT NULL,
  `idc_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `sn` INT NULL DEFAULT NULL,
  `enable_time` DATETIME NULL DEFAULT NULL,
  `due_time` DATETIME NULL DEFAULT NULL,
  `accessory_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `store_id` BIGINT(20) UNSIGNED NOT NULL,
  `asset_id` BIGINT(20) UNSIGNED NULL,
  `brand_id` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_accessory_t_accessory_type1_idx` (`accessory_type_id` ASC),
  INDEX `fk_t_accessory_t_accessory_store1_idx` (`store_id` ASC),
  INDEX `fk_t_accessory_4_idx` (`brand_id` ASC),
  INDEX `fk_t_accessory_3_idx` (`asset_id` ASC),
  CONSTRAINT `fk_t_accessory_1`
    FOREIGN KEY (`accessory_type_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory_type` (`accessory_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_accessory_2`
    FOREIGN KEY (`store_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory_store` (`accessory_store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_accessory_3`
    FOREIGN KEY (`asset_id`)
    REFERENCES `dbwww58com_cmdb`.`t_asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_accessory_4`
    FOREIGN KEY (`brand_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory_brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_cpu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_cpu` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_cpu` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `cpu_model` VARCHAR(45) NULL DEFAULT NULL,
  `cpu_core` INT NULL DEFAULT NULL,
  `cpu_frequency` FLOAT NULL DEFAULT NULL,
  `cpu_power` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `platform_type` VARCHAR(45) NULL DEFAULT NULL,
  `cpu_ht_support` TINYINT NULL DEFAULT NULL,
  `cpu_vm_support` TINYINT NULL DEFAULT NULL,
  `cpu_memory_channel_num` INT NULL DEFAULT NULL,
  `cpu_max_num` INT NULL DEFAULT NULL,
  `cpu_node_support` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t _cpu_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t _cpu_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_memory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_memory` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_memory` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `memory_capacity` INT NULL DEFAULT NULL,
  `memroy_frequency` INT NULL DEFAULT NULL,
  `memory_model` VARCHAR(45) NULL DEFAULT NULL,
  `memory_specs` VARCHAR(45) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `memory_ecc_support` TINYINT NULL DEFAULT NULL,
  `memory_channel_num` INT NULL DEFAULT NULL,
  `memory_max_underclocking` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_memory_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_memory_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_disk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_disk` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_disk` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `disk_capacity` INT NULL DEFAULT NULL,
  `disk_interface` TINYINT NULL DEFAULT NULL,
  `disk_speed` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `disk_model` VARCHAR(45) NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `bandwidth` INT NULL DEFAULT NULL,
  `iops` INT NULL DEFAULT NULL,
  `disk_type` TINYINT NULL DEFAULT NULL,
  `disk_cache` INT NULL DEFAULT NULL,
  `disk_chip` VARCHAR(45) NULL DEFAULT NULL,
  `disk_nand` INT NULL DEFAULT NULL,
  `disk_nand_process` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_disk_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_disk_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_network_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_network_card` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_network_card` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `speed` INT NULL DEFAULT NULL,
  `network_card_interface` TINYINT NULL DEFAULT NULL,
  `network_card_model` VARCHAR(45) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `mac_address` VARCHAR(45) NULL DEFAULT NULL,
  `network_card_iscsi_support` TINYINT NULL DEFAULT NULL,
  `network_card_ncsi_support` TINYINT NULL DEFAULT NULL,
  `network_card_pxe_support` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_network_card_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_network_card_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_power`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_power` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_power` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `power_model` VARCHAR(45) NULL DEFAULT NULL,
  `power_specs` TINYINT NULL DEFAULT NULL,
  `efficiency` INT NULL DEFAULT NULL,
  `power_supply` TINYINT NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_t_power_t_accessory1_idx` (`accessory_id` ASC),
  PRIMARY KEY (`accessory_id`),
  CONSTRAINT `fk_t_power_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_mother_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_mother_board` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_mother_board` (
  `accessory_id` BIGINT UNSIGNED NOT NULL,
  `mother_board_model` VARCHAR(45) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `pci_count` INT NULL DEFAULT NULL,
  `pcie_count` INT NULL DEFAULT NULL,
  `sata_count` INT NULL DEFAULT NULL,
  `sas_count` INT NULL DEFAULT NULL,
  `m_2_count` INT NULL DEFAULT NULL,
  `satadom_count` INT NULL DEFAULT NULL,
  `lom_count` INT NULL DEFAULT NULL,
  `dimm_count` INT NULL DEFAULT NULL,
  `mother_board_chip` VARCHAR(45) NULL DEFAULT NULL,
  `sd_support` TINYINT NULL DEFAULT NULL,
  `sata_controller_support` TINYINT NULL DEFAULT NULL,
  `sas_controller_support` TINYINT NULL DEFAULT NULL,
  `usb_count` INT NULL DEFAULT NULL,
  `double_bios_protection_support` TINYINT NULL DEFAULT NULL,
  `asset_entry_support` TINYINT NULL DEFAULT NULL,
  `command_bios_support` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_mother_board_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_mother_board_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_array_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_array_card` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_array_card` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `array_card_interface` TINYINT NULL DEFAULT NULL,
  `array_card_cache` INT NULL DEFAULT NULL,
  `array_card_buttery` TINYINT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `cache_status` TINYINT NULL DEFAULT NULL,
  `strip_size` INT NULL DEFAULT NULL,
  `read_write_ratio` VARCHAR(45) NULL DEFAULT NULL,
  `array_card_model` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_array_card_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_array_card_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_hba_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_hba_card` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_hba_card` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `hba_card_interface` TINYINT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `hba_card_model` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_hba_card_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_hba_card_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_fan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_fan` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_fan` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `fan_redundancy_level` INT NULL DEFAULT NULL,
  `fan_max_speed` INT NULL DEFAULT NULL,
  `fan_auto_regulation_support` TINYINT NULL DEFAULT NULL,
  `fan_position` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_fan_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_fan_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_guide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_guide` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_guide` (
  `guide_id` INT UNSIGNED NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `used` INT NULL DEFAULT NULL,
  `total_count` INT NULL DEFAULT NULL,
  `guide_model` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`guide_id`),
  UNIQUE INDEX `guide_model_UNIQUE` (`guide_model` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_gpu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_gpu` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_gpu` (
  `accessory_id` BIGINT(20) UNSIGNED NOT NULL,
  `gpu_core_num` INT NULL DEFAULT NULL,
  `gpu_memory` INT NULL DEFAULT NULL,
  `gpu_frequency` INT NULL DEFAULT NULL,
  `gpu_chip` VARCHAR(45) NULL DEFAULT NULL,
  `gpu_memory_specs` VARCHAR(45) NULL DEFAULT NULL,
  `gpu_power` INT NULL DEFAULT NULL,
  `gpu_idle_power` INT NULL DEFAULT NULL,
  `gpu_memory_bandwidth` INT NULL DEFAULT NULL,
  PRIMARY KEY (`accessory_id`),
  INDEX `fk_t_gpu_t_accessory1_idx` (`accessory_id` ASC),
  CONSTRAINT `fk_t_gpu_t_accessory1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `dbwww58com_cmdb`.`t_accessory` (`accessory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_org`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_org` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_org` (
  `org_id` BIGINT(20) UNSIGNED NOT NULL,
  `org_pid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `org_level` TINYINT(4) NULL DEFAULT NULL,
  `org_name` VARCHAR(255) NULL DEFAULT NULL,
  `org_operator_ids` VARCHAR(255) NULL DEFAULT NULL,
  `org_manager_ids` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`org_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_cluster` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_cluster` (
  `cluster_id` BIGINT(20) UNSIGNED NOT NULL,
  `cluster_name` VARCHAR(255) NULL DEFAULT NULL,
  `cluster_manager_ids` VARCHAR(255) NULL DEFAULT NULL,
  `org_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`cluster_id`),
  INDEX `org_id` (`org_id` ASC),
  CONSTRAINT `idx_cluster_org`
    FOREIGN KEY (`org_id`)
    REFERENCES `dbwww58com_cmdb`.`t_org` (`org_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_dpt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_dpt` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_dpt` (
  `bsp_dpt_id` CHAR(22) NOT NULL,
  `dpt_level` TINYINT(4) NULL DEFAULT NULL,
  `dpt_name` VARCHAR(255) NULL DEFAULT NULL,
  `bsp_dpt_p_id` CHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`bsp_dpt_id`),
  INDEX `bsp_dpt_p_id` (`bsp_dpt_p_id` ASC),
  CONSTRAINT ` idx_dpt_pid`
    FOREIGN KEY (`bsp_dpt_p_id`)
    REFERENCES `dbwww58com_cmdb`.`t_dpt` (`bsp_dpt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_org_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_org_user` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_org_user` (
  `bsp_user_id` CHAR(50) NOT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  `user_real_name` VARCHAR(255) NULL DEFAULT NULL,
  `user_email` VARCHAR(255) NULL DEFAULT NULL,
  `user_mobile` VARCHAR(255) NULL DEFAULT NULL,
  `user_tel` VARCHAR(50) NULL DEFAULT NULL,
  `user_child_tel` VARCHAR(255) NULL DEFAULT NULL,
  `user_gender` CHAR(2) NULL DEFAULT NULL,
  `employ_id` VARCHAR(255) NULL DEFAULT NULL,
  `qq` VARCHAR(255) NULL DEFAULT NULL,
  `bsp_leader_id` CHAR(22) NULL DEFAULT NULL,
  `org_dpt_id` CHAR(22) NULL DEFAULT NULL,
  `dpt_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`bsp_user_id`),
  INDEX `bsp_leader_id` (`bsp_leader_id` ASC),
  INDEX `org_dpt_id` (`org_dpt_id` ASC),
  CONSTRAINT `idx_org_dpt`
    FOREIGN KEY (`org_dpt_id`)
    REFERENCES `dbwww58com_cmdb`.`t_dpt` (`bsp_dpt_id`),
  CONSTRAINT `idx_pid`
    FOREIGN KEY (`bsp_leader_id`)
    REFERENCES `dbwww58com_cmdb`.`t_org_user` (`bsp_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_ip_segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_ip_segment` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_ip_segment` (
  `ip_segment_id` BIGINT(20) UNSIGNED NOT NULL,
  `ip_segment_address` VARCHAR(255) NULL DEFAULT NULL,
  `ip_segment_netmask` VARCHAR(255) NULL DEFAULT NULL,
  `ip_segment_isp` VARCHAR(255) NULL DEFAULT NULL,
  `vlan_Id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `ip_segment_gateway` VARCHAR(255) NULL DEFAULT NULL,
  `ip_segment_broadcast` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `ip_segment_id` (`ip_segment_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_ip_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_ip_address` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_ip_address` (
  `ip_address_id` BIGINT(20) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(255) NULL DEFAULT NULL,
  `assign_time` DATETIME NULL DEFAULT NULL,
  `update_time` DATETIME NULL DEFAULT NULL,
  `ip_status` TINYINT(4) NULL DEFAULT NULL,
  `asset_id` INT(11) NULL DEFAULT NULL,
  `ip_type` TINYINT(4) NULL DEFAULT NULL,
  `ip_segment_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `ip_assigner_id` CHAR(50) NULL DEFAULT NULL,
  `ip_segment_name` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `ip_segment_id` (`ip_segment_id` ASC),
  INDEX `ip_assigner_id` (`ip_assigner_id` ASC),
  PRIMARY KEY (`ip_address_id`),
  CONSTRAINT `idx_user`
    FOREIGN KEY (`ip_assigner_id`)
    REFERENCES `dbwww58com_cmdb`.`t_org_user` (`bsp_user_id`),
  CONSTRAINT `idx_ip_segment`
    FOREIGN KEY (`ip_segment_id`)
    REFERENCES `dbwww58com_cmdb`.`t_ip_segment` (`ip_segment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbwww58com_cmdb`.`t_org_dpt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbwww58com_cmdb`.`t_org_dpt` ;

CREATE TABLE IF NOT EXISTS `dbwww58com_cmdb`.`t_org_dpt` (
  `org_dpt_id` BIGINT(20) UNSIGNED NOT NULL,
  `bsp_dpt_id` CHAR(22) NULL DEFAULT NULL,
  `org_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  INDEX `bsp_dpt_id` (`bsp_dpt_id` ASC),
  INDEX `org_id` (`org_id` ASC),
  PRIMARY KEY (`org_dpt_id`),
  CONSTRAINT `idx_dpt_dpt`
    FOREIGN KEY (`org_id`)
    REFERENCES `dbwww58com_cmdb`.`t_org` (`org_id`),
  CONSTRAINT `idx_dpt_org`
    FOREIGN KEY (`bsp_dpt_id`)
    REFERENCES `dbwww58com_cmdb`.`t_dpt` (`bsp_dpt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
