# -*- coding: utf-8 -*-

from models.datacenter import Datacenter
from models.device import Device
from models.device_category import DeviceCategory
from models.device_ip import DeviceIp
from models.remote_card import RemoteCard
from models.host import Host
from models.host_ip import HostIp
from models.host_operation_history import HostOperationHistory
from models.ip_address import IpAddress
from models.log import Log
from models.pool import Pool
from models.pool_config import PoolConfig
from models.pool_host import PoolHost
from models.rack import Rack
from models.supplier import Supplier
from models.user import User
from models.tasks import Tasks
from models.follow import Follow
from models.vm import Vm
from models.role import Role
from models.user_role import UserRole
from models.action import Action
from models.role_action import RoleAction
from models.ip_blacklist import IpBlacklist
from models.alarm import Alarm
from models.sshkey import Sshkey
from models.host_load_ratio import HostLoadRatio
from models.host_load_daily import HostLoadDaily
from models.pool_load_ratio import PoolLoadRatio
from models.pool_load_daily import PoolLoadDaily
from models.host_bastion_apply import HostBastionApply
from models.host_bastion_tasks import HostBastionTasks
from models.user_host import UserHost
from models.mail_queue import MailQueue
from models.pubkey_changed_queue import PubkeyChangedQueue
from models.stock_parts_model import StockPartsModel
from models.stock_parts import StockParts
from models.stock_history import StockHistory
from models.apply import  Apply
from models.apply_host_tasks import ApplyHostTasks
from models.apply_host import Apply_host
from models.sa.tickets_category import Tickets_Category
from models.sa.tickets import Tickets
from models.sa.tickets_task import Tickets_Task
from models.sa.tickets_comments import Tickets_Comments
from models.orders.order_category import Order_Category
from models.orders.order_comments import Order_Comments
from models.orders.ordercat_type import Ordercat_Type
from models.orders.orders import  Orders
from models.orders.orders_task import Orders_Task
from models.dns.dns_apply import DnsApply
from models.dns.dns_zone import DnsZone
from models.dns.dns_history import DnsHistory
from models.dns.dns_tasks import DnsTasks
from models.dns.cdn import Cdn
from models.dns.cdn_details import CdnDetails
from models.jobplat import Jobplat
from models.user import *
from models.puv import *
from models.work import *

